FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY AuthenticationService/AuthService/AuthService.sln ./
COPY AuthenticationService/AuthService/src/AuthService.Domain/ src/AuthService.Domain/
COPY AuthenticationService/AuthService/src/AuthService.Persistence/ src/AuthService.Persistence/
COPY AuthenticationService/AuthService/src/AuthService.Application/ src/AuthService.Application/
COPY AuthenticationService/AuthService/src/AuthService.Api/ src/AuthService.Api/

RUN dotnet restore AuthService.sln
RUN dotnet publish src/AuthService.Api/AuthService.Api.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production


ENTRYPOINT ["sh", "-c", "ASPNETCORE_URLS=http://+:${PORT:-10000} exec dotnet AuthService.Api.dll"]