export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    CHANGE_TEMP_PASSWORD: '/auth/change-temp-password',
    PROFILE: '/auth/profile',
    ADMIN_USERS: '/auth/admin/users',
    ADMIN_USERS_SUMMARY: '/auth/admin/users/summary',
    ME: '/auth/me',
    ADMIN_CREATE_USER: '/auth/admin/create-user',
    ADMIN_DELETE_USER: '/auth/admin/users',
    RESEND_VERIFICATION: '/auth/resend-verification',
  },
  ACCOUNT: {
    ACCOUNTS: '/accounts',
    ACCOUNT_BY_ID: '/accounts',
    MY_ACCOUNTS: '/accounts',
    FAVORITES: '/favorite',
    FAVORITE_BY_ID: '/favorite',
    QUICK_TRANSFER: '/transfers/quick',
    MY_NOTIFICATIONS: '/notifications/my',
    NOTIFICATION_READ: '/notifications',
    ACCOUNT_HISTORY: '/history/account',
    DEPOSITS: '/deposits',
    DEPOSIT_REVERT: '/deposits',
    DEPOSITS_CURRENCY: '/deposits/currency',
    TRANSFERS: '/transfers',
    TRANSFERS_CONFIRM: '/transfers/confirm',
    TRANSFERS_CURRENCY: '/transfers/currency',
    TRANSFERS_DAILY_LIMIT: '/transfers/daily-limit',
    HISTORY_BANK: '/history/bank/movements',
    ACCOUNTS_ADMIN_SUMMARY: '/accounts/admin/summary',
    ACCOUNTS_ADMIN_ALL: '/accounts/admin/all',
    ACCOUNTS_ADMIN_STATUS: '/accounts/admin',
  },
  PRODUCT: {
    PRODUCTS: '/products',
    PRODUCT_BY_ID: '/products',
    PRODUCT_IMAGE: '/products',
    TRANSACTIONS_BUY: '/transactions/buy',
    MY_TRANSACTIONS: '/transactions/my-transactions',
  },
};

export const API_BASE_URLS = {
  AUTH: process.env.EXPO_PUBLIC_AUTH_URL || 'http://localhost:5079/api/v1',
  ACCOUNT: process.env.EXPO_PUBLIC_ACCOUNT_URL || 'http://localhost:3010/chapinbank/v1',
  PRODUCT: process.env.EXPO_PUBLIC_PRODUCT_URL || 'http://localhost:3015/chapinbank/v1',
};
